package com.cyou.cma.clockscreen.quicklaunch;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LAUNCH_SET.
 */
public class LaunchSet {

    private Long id;
    private Integer tag;
    private Integer type =0;

    public LaunchSet() {
    }

    public LaunchSet(Long id) {
        this.id = id;
    }

    public LaunchSet(Long id, Integer tag, Integer type) {
        this.id = id;
        this.tag = tag;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getTag() {
        return tag;
    }

    public void setTag(Integer tag) {
        this.tag = tag;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

}
