package com.cyou.cma.clockscreen.quicklaunch;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table QUICK_CONTACT.
 */
public class QuickContact {

    private Long id;
    /** Not-null value. */
    private String contactName;
    /** Not-null value. */
    private String contactNumber;
    private String photoUri;
    private Long launchSetIdOfContact;
    private Long folderIdOfContact;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient QuickContactDao myDao;

    private LaunchSet launchSet;
    private Long launchSet__resolvedKey;

    private QuickFolder quickFolder;
    private Long quickFolder__resolvedKey;


    public QuickContact() {
    }

    public QuickContact(Long id) {
        this.id = id;
    }

    public QuickContact(Long id, String contactName, String contactNumber, String photoUri, Long launchSetIdOfContact, Long folderIdOfContact) {
        this.id = id;
        this.contactName = contactName;
        this.contactNumber = contactNumber;
        this.photoUri = photoUri;
        this.launchSetIdOfContact = launchSetIdOfContact;
        this.folderIdOfContact = folderIdOfContact;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getQuickContactDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getContactName() {
        return contactName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    /** Not-null value. */
    public String getContactNumber() {
        return contactNumber;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContactNumber(String contactNumber) {
        this.contactNumber = contactNumber;
    }

    public String getPhotoUri() {
        return photoUri;
    }

    public void setPhotoUri(String photoUri) {
        this.photoUri = photoUri;
    }

    public Long getLaunchSetIdOfContact() {
        return launchSetIdOfContact;
    }

    public void setLaunchSetIdOfContact(Long launchSetIdOfContact) {
        this.launchSetIdOfContact = launchSetIdOfContact;
    }

    public Long getFolderIdOfContact() {
        return folderIdOfContact;
    }

    public void setFolderIdOfContact(Long folderIdOfContact) {
        this.folderIdOfContact = folderIdOfContact;
    }

    /** To-one relationship, resolved on first access. */
    public LaunchSet getLaunchSet() {
        Long __key = this.launchSetIdOfContact;
        if (launchSet__resolvedKey == null || !launchSet__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            LaunchSetDao targetDao = daoSession.getLaunchSetDao();
            LaunchSet launchSetNew = targetDao.load(__key);
            synchronized (this) {
                launchSet = launchSetNew;
            	launchSet__resolvedKey = __key;
            }
        }
        return launchSet;
    }

    public void setLaunchSet(LaunchSet launchSet) {
        synchronized (this) {
            this.launchSet = launchSet;
            launchSetIdOfContact = launchSet == null ? null : launchSet.getId();
            launchSet__resolvedKey = launchSetIdOfContact;
        }
    }

    /** To-one relationship, resolved on first access. */
    public QuickFolder getQuickFolder() {
        Long __key = this.folderIdOfContact;
        if (quickFolder__resolvedKey == null || !quickFolder__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            QuickFolderDao targetDao = daoSession.getQuickFolderDao();
            QuickFolder quickFolderNew = targetDao.load(__key);
            synchronized (this) {
                quickFolder = quickFolderNew;
            	quickFolder__resolvedKey = __key;
            }
        }
        return quickFolder;
    }

    public void setQuickFolder(QuickFolder quickFolder) {
        synchronized (this) {
            this.quickFolder = quickFolder;
            folderIdOfContact = quickFolder == null ? null : quickFolder.getId();
            quickFolder__resolvedKey = folderIdOfContact;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
