package com.cyou.cma.clockscreen.quicklaunch;

import java.util.ArrayList;
import java.util.List;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table QUICK_APPLICATION.
*/
public class QuickApplicationDao extends AbstractDao<QuickApplication, Long> {

    public static final String TABLENAME = "QUICK_APPLICATION";

    /**
     * Properties of entity QuickApplication.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PackageName = new Property(1, String.class, "packageName", false, "PACKAGE_NAME");
        public final static Property MainActivityClassName = new Property(2, String.class, "mainActivityClassName", false, "MAIN_ACTIVITY_CLASS_NAME");
        public final static Property LaunchSetIdOfApplication = new Property(3, Long.class, "launchSetIdOfApplication", false, "LAUNCH_SET_ID_OF_APPLICATION");
        public final static Property FolderIdOfApplication = new Property(4, Long.class, "folderIdOfApplication", false, "FOLDER_ID_OF_APPLICATION");
    };

    private DaoSession daoSession;

    private Query<QuickApplication> quickFolder_QuickApplicationListQuery;

    public QuickApplicationDao(DaoConfig config) {
        super(config);
    }
    
    public QuickApplicationDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'QUICK_APPLICATION' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'PACKAGE_NAME' TEXT NOT NULL ," + // 1: packageName
                "'MAIN_ACTIVITY_CLASS_NAME' TEXT NOT NULL ," + // 2: mainActivityClassName
                "'LAUNCH_SET_ID_OF_APPLICATION' INTEGER," + // 3: launchSetIdOfApplication
                "'FOLDER_ID_OF_APPLICATION' INTEGER);"); // 4: folderIdOfApplication
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'QUICK_APPLICATION'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, QuickApplication entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getPackageName());
        stmt.bindString(3, entity.getMainActivityClassName());
 
        Long launchSetIdOfApplication = entity.getLaunchSetIdOfApplication();
        if (launchSetIdOfApplication != null) {
            stmt.bindLong(4, launchSetIdOfApplication);
        }
 
        Long folderIdOfApplication = entity.getFolderIdOfApplication();
        if (folderIdOfApplication != null) {
            stmt.bindLong(5, folderIdOfApplication);
        }
    }

    @Override
    protected void attachEntity(QuickApplication entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public QuickApplication readEntity(Cursor cursor, int offset) {
        QuickApplication entity = new QuickApplication( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // packageName
            cursor.getString(offset + 2), // mainActivityClassName
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // launchSetIdOfApplication
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // folderIdOfApplication
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, QuickApplication entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPackageName(cursor.getString(offset + 1));
        entity.setMainActivityClassName(cursor.getString(offset + 2));
        entity.setLaunchSetIdOfApplication(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setFolderIdOfApplication(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(QuickApplication entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(QuickApplication entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "quickApplicationList" to-many relationship of QuickFolder. */
    public List<QuickApplication> _queryQuickFolder_QuickApplicationList(Long folderIdOfApplication) {
        synchronized (this) {
            if (quickFolder_QuickApplicationListQuery == null) {
                QueryBuilder<QuickApplication> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.FolderIdOfApplication.eq(null));
                quickFolder_QuickApplicationListQuery = queryBuilder.build();
            }
        }
        Query<QuickApplication> query = quickFolder_QuickApplicationListQuery.forCurrentThread();
        query.setParameter(0, folderIdOfApplication);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getLaunchSetDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getQuickFolderDao().getAllColumns());
            builder.append(" FROM QUICK_APPLICATION T");
            builder.append(" LEFT JOIN LAUNCH_SET T0 ON T.'LAUNCH_SET_ID_OF_APPLICATION'=T0.'_id'");
            builder.append(" LEFT JOIN QUICK_FOLDER T1 ON T.'FOLDER_ID_OF_APPLICATION'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected QuickApplication loadCurrentDeep(Cursor cursor, boolean lock) {
        QuickApplication entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        LaunchSet launchSet = loadCurrentOther(daoSession.getLaunchSetDao(), cursor, offset);
        entity.setLaunchSet(launchSet);
        offset += daoSession.getLaunchSetDao().getAllColumns().length;

        QuickFolder quickFolder = loadCurrentOther(daoSession.getQuickFolderDao(), cursor, offset);
        entity.setQuickFolder(quickFolder);

        return entity;    
    }

    public QuickApplication loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<QuickApplication> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<QuickApplication> list = new ArrayList<QuickApplication>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<QuickApplication> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<QuickApplication> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
