package com.cyou.cma.clockscreen.quicklaunch;

import java.util.ArrayList;
import java.util.List;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.internal.SqlUtils;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table QUICK_FOLDER.
*/
public class QuickFolderDao extends AbstractDao<QuickFolder, Long> {

    public static final String TABLENAME = "QUICK_FOLDER";

    /**
     * Properties of entity QuickFolder.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property FolderName = new Property(1, String.class, "folderName", false, "FOLDER_NAME");
        public final static Property SubCount = new Property(2, Integer.class, "subCount", false, "SUB_COUNT");
        public final static Property LaunchSetIdOfFolder = new Property(3, Long.class, "launchSetIdOfFolder", false, "LAUNCH_SET_ID_OF_FOLDER");
    };

    private DaoSession daoSession;


    public QuickFolderDao(DaoConfig config) {
        super(config);
    }
    
    public QuickFolderDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'QUICK_FOLDER' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'FOLDER_NAME' TEXT NOT NULL ," + // 1: folderName
                "'SUB_COUNT' INTEGER," + // 2: subCount
                "'LAUNCH_SET_ID_OF_FOLDER' INTEGER);"); // 3: launchSetIdOfFolder
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'QUICK_FOLDER'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, QuickFolder entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getFolderName());
 
        Integer subCount = entity.getSubCount();
        if (subCount != null) {
            stmt.bindLong(3, subCount);
        }
 
        Long launchSetIdOfFolder = entity.getLaunchSetIdOfFolder();
        if (launchSetIdOfFolder != null) {
            stmt.bindLong(4, launchSetIdOfFolder);
        }
    }

    @Override
    protected void attachEntity(QuickFolder entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public QuickFolder readEntity(Cursor cursor, int offset) {
        QuickFolder entity = new QuickFolder( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // folderName
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // subCount
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // launchSetIdOfFolder
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, QuickFolder entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFolderName(cursor.getString(offset + 1));
        entity.setSubCount(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setLaunchSetIdOfFolder(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(QuickFolder entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(QuickFolder entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getLaunchSetDao().getAllColumns());
            builder.append(" FROM QUICK_FOLDER T");
            builder.append(" LEFT JOIN LAUNCH_SET T0 ON T.'LAUNCH_SET_ID_OF_FOLDER'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected QuickFolder loadCurrentDeep(Cursor cursor, boolean lock) {
        QuickFolder entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        LaunchSet launchSet = loadCurrentOther(daoSession.getLaunchSetDao(), cursor, offset);
        entity.setLaunchSet(launchSet);

        return entity;    
    }

    public QuickFolder loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<QuickFolder> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<QuickFolder> list = new ArrayList<QuickFolder>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<QuickFolder> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<QuickFolder> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
